version: "3"
services:
  db:
    image: mysql:8.0-ubuntu20.04
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - 3306:3306
    volumes:
      - ./:/0x0F
